import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import './globals.css';
import { Providers } from './providers';
import { Metadata } from 'next';
import GoogleAdsense from '@/components/GoogleAdsense';

const fontHeading = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-heading',
});

const fontBody = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-body',
});

export const metadata: Metadata = {
    title: 'Rotating Schedule Builder',
    description: 'Generated by create next app',

};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <GoogleAdsense />
            <body
                className={cn(
                    'antialiased',
                    fontHeading.variable,
                    fontBody.variable
                )}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
